### ISSUE TITLE
A proble when I use

### ISSUE THREAD

**Issue by VictorCSheng** [PyJEM/PyJEM#1]
When I execute from a remote place, I receive a problem like this.
“PyJEM could not access TEMCenter. However, TEM3 can be used.”
What should I do to solve this problem

**Comment by dmaekawa** [comment]
Sorry for the late reply. 
I think this issue can be solved by setting PyJEM to be used remotely. 
Please tell me the version of PyJEM to solve this problem.

**Comment by VictorCSheng** [comment]
The version of the PyJEM is 1.0.2.1143, and our TEM is JEM-F200.

**Comment by dmaekawa** [comment]
Thanks.
Do the following two tasks. 

1. Execute remote function 
   `import PyJEM 
    PyJEM.remote()`

2. Edit config file.
    (i) Open "C:\.....\PyJEM\config.ini"
    (ii) Change "hostpc = local" to "hostpc = remote"

**Comment by VictorCSheng** [comment]
I can connect TEM with your method. Thank you very much. I have another question. We have added a Gatan camera to shoot some special images. Can I control the Gatan camera to shoot through PyJEM?

**Comment by PyJEM** [comment]
I'm glad the problem was solved.

sorry. 
Current PyJEM does not support Gatan camera control.

**Comment by VictorCSheng** [comment]
Is there any other way to realize the linkage control of the JEM-F200 and Gatan OneView camera?

**Comment by PyJEM** [comment]
JEM-F200 can be controlled by the Python3.5 using PyJEM.
Ask the manufacturer if you can control Gatan's OneView camera with Python.

**Comment by VictorCSheng** [comment]
Thank you
