### ISSUE TITLE
Reset Free Lens Control

### ISSUE THREAD

**Issue by rfwebster** [PyJEM/PyJEM#7]
When changing the lens current values, I use:
`TEM3.lens.SetFLCAbs(0, 4000)'
I believe this uses the free lens control?
Is there an easy way to reset all the changed values back to their original values - i.e. before the script ran (I currently make a backup of the values before changing anything then at the end change them all back manually)

**Comment by PyJEM** [comment]
Sorry for the late reply.
It is possible to reset the changed lens value.
You can run 'TEM3.lens.SetFLCSwAllLens(0)' to reset all lens values. if you want to change the value of a single lens, use 'TEM3.lens.SetFLCSw(_lensID_, 0)'.
